ODSWIEZANIE: 60
LICZBA_PROB_W_TRENINGU: 20
LICZBA_POWTORZEN_TRENINGU: 1
LICZBA_PROB_W_EKSPERYMENCIE: 75
LICZBA_POWTORZEN_EKSPERYMENTU: 3
KOLOR_TLA: '#777777'
PRZYCISK_KONTYNUACJI: ['space']
PRZYCISK_WYJSCIA: ['escape']
ROZMAR_TEKSTU: 0.04
RODZAJ_PUNKTU_FIKSACJI: '+'
KOLOR_PUNKTU_FIKSACJI: '#000000'
KOLOR_TEKSTU: '#000000'
KOLOR_KRAWEDZI_PROSTOKATA: '#000000'
KOLOR_PROSTOKATA: '#777777'
ROZMIAR_PROSTOKATA: 0.3
CZAS_WYSWIETLANIA_PUNKTU_FIKSACJI: 1
CZAS_NA_REAKCJE: 3
PRZERWA: 1
ROZMAR_BODZCA: 0.1
POPRAWNOSC: ['Źle', 'Dobrze']
NAGLOWKI_TABELI_WYNIKOW: ['Eksperyment', 'Numer proby', 'Zgodnosc bodzca', 'Reakcja', 'Bodziec', 'Kolor bodzca', 'Poprawnosc odpowiedzi', 'Czas reakcji']
KOLORY: [{
  napis: 'Zielony',
  kolor: '#00FF00',
  przycisk: 'z'
},{
  napis: 'Czerwony',
  kolor: '#FF0000',
  przycisk: 'c'
},{
  napis: 'Niebieski',
  kolor: '#0000FF',
  przycisk: 'n'
},{
  napis: 'Żółty',
  kolor: '#FFFF00',
  przycisk: 'k'
},{
  napis: '@#$%&'
}]
